# id for the world
id = "minter_world"

# top level id for the `TokenAdmin` agent
[[admin]]
# named struct and arguments for initializing the `TokenAdmin` agent
TokenAdmin = { max_count = 4, token_data = { "US Dollar Coin" = { name = "US Dollar Coin", symbol = "USDC", decimals = 18 } } }


# top level id for the `TokenRequester` agent
[[requester]]
# named struct and arguments for initializing the `TokenRequester` agent
TokenRequester = { max_count = 3, request_to = "admin", token_data = { name = "US Dollar Coin", symbol = "USDC", decimals = 18 } }
