name: book

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Rust
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Install mdbook
      - name: Install mdbook
        run: cargo install mdbook --vers "^0.4.35"

      # Install mdbook-katex
      - name: Install mdbook-katex
        run: cargo install mdbook-katex

      # Build book
      - name: build book
        run: mdbook build

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Install Rust
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      # Install mdbook-linkcheck
      - name: Install mdbook-linkcheck
        run: cargo install mdbook-linkcheck
      
      - name: linkcheck
        run: mdbook-linkcheck --standalone

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Install Rust
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: test
        run: |
          cd docs
          cargo test