name: test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "arbiter-bindings/*"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: test
        run: cargo test --workspace --all-features
